package com.zuoer.sofa.blog.dal.dao;

import com.zuoer.sofa.blog.dal.dateobject.AdminUserDO;
import java.util.List;

public interface AdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    java.util.List<AdminUserDO> selectByEmail(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    java.util.List<AdminUserDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    Long insert(AdminUserDO insertDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    AdminUserDO selectById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    AdminUserDO selectByUserName(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    AdminUserDO selectByIds(java.util.List ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    int deleteByIds(java.util.List ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    int updateById(AdminUserDO insertDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    int updateEmailById(String email, Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    int updateByIds(java.util.List ids);
}