package com.zuoer.sofa.blog.dal.dao;

import com.zuoer.sofa.blog.dal.dateobject.ArticleDO;
import java.util.List;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbg.generated
     */
    ArticleDO selectById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbg.generated
     */
    Long insert(ArticleDO insertDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbg.generated
     */
    int deleteByIds(java.util.List ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbg.generated
     */
    int updateById(ArticleDO insertDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbg.generated
     */
    java.util.List<ArticleDO> selectAll();
}