package com.zuoer.sofa.blog.dal.dao;

import com.zuoer.sofa.blog.dal.dateobject.TagArticleDO;

public interface TagArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAG_ARTICLE
     *
     * @mbg.generated
     */
    TagArticleDO selectById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAG_ARTICLE
     *
     * @mbg.generated
     */
    Long insert(TagArticleDO insertDO);
}