package com.zuoer.sofa.blog.dal.dao;

import com.zuoer.sofa.blog.dal.dateobject.TagDO;
import java.util.List;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAG
     *
     * @mbg.generated
     */
    TagDO selectById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAG
     *
     * @mbg.generated
     */
    Long insert(TagDO insertDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAG
     *
     * @mbg.generated
     */
    TagDO selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAG
     *
     * @mbg.generated
     */
    java.util.List<TagDO> selectAll();
}