package com.zuoer.sofa.blog.dal.dao;

import com.zuoer.sofa.blog.dal.dateobject.UserBaseDO;
import java.util.List;

public interface UserBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbg.generated
     */
    UserBaseDO selectByEmail(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbg.generated
     */
    UserBaseDO selectByUserName(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbg.generated
     */
    Long insert(UserBaseDO insertDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbg.generated
     */
    java.util.List<UserBaseDO> selectAll();
}