package com.zuoer.sofa.blog.dal.dao;

import com.zuoer.sofa.blog.dal.dateobject.AdminUser;
import com.zuoer.sofa.blog.dal.dateobject.AdminUserKey;
import java.util.List;

public interface AdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    java.util.List<AdminUser> selectByEmail(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    AdminUserKey insert(AdminUser insertDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    AdminUser selectById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    AdminUser selectByIds(java.util.List ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    int updateById(AdminUser insertDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    int updateEmailById(String email, Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbg.generated
     */
    int updateByIds(java.util.List ids);
}