package com.zuoer.sofa.blog.dal.dao;

import com.zuoer.sofa.blog.dal.dateobject.Article;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARTICLE
     *
     * @mbg.generated
     */
    Article selectByEmail(Long id);
}