package com.zuoer.sofa.blog.dal.dao;

import com.zuoer.sofa.blog.dal.dateobject.TagArticle;

public interface TagArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAG_ARTICLE
     *
     * @mbg.generated
     */
    TagArticle selectByEmail(Long id);
}