package com.zuoer.sofa.blog.dal.dao;

import com.zuoer.sofa.blog.dal.dateobject.TagDO;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAG
     *
     * @mbg.generated
     */
    TagDO selectByEmail(Long id);
}