package com.zuoer.sofa.blog.dal.dateobject;

import java.util.Date;

public class ResumeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESUME.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESUME.GMT_CREATE
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESUME.GMT_MODIFIED
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESUME.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESUME.INTRODUCTION
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESUME.MD_MATERIAL
     *
     * @mbg.generated
     */
    private String mdMaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESUME.HTML_MATERIAL
     *
     * @mbg.generated
     */
    private String htmlMaterial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESUME.ID
     *
     * @return the value of RESUME.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESUME.ID
     *
     * @param id the value for RESUME.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESUME.GMT_CREATE
     *
     * @return the value of RESUME.GMT_CREATE
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESUME.GMT_CREATE
     *
     * @param gmtCreate the value for RESUME.GMT_CREATE
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESUME.GMT_MODIFIED
     *
     * @return the value of RESUME.GMT_MODIFIED
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESUME.GMT_MODIFIED
     *
     * @param gmtModified the value for RESUME.GMT_MODIFIED
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESUME.TITLE
     *
     * @return the value of RESUME.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESUME.TITLE
     *
     * @param title the value for RESUME.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESUME.INTRODUCTION
     *
     * @return the value of RESUME.INTRODUCTION
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESUME.INTRODUCTION
     *
     * @param introduction the value for RESUME.INTRODUCTION
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESUME.MD_MATERIAL
     *
     * @return the value of RESUME.MD_MATERIAL
     *
     * @mbg.generated
     */
    public String getMdMaterial() {
        return mdMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESUME.MD_MATERIAL
     *
     * @param mdMaterial the value for RESUME.MD_MATERIAL
     *
     * @mbg.generated
     */
    public void setMdMaterial(String mdMaterial) {
        this.mdMaterial = mdMaterial == null ? null : mdMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESUME.HTML_MATERIAL
     *
     * @return the value of RESUME.HTML_MATERIAL
     *
     * @mbg.generated
     */
    public String getHtmlMaterial() {
        return htmlMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESUME.HTML_MATERIAL
     *
     * @param htmlMaterial the value for RESUME.HTML_MATERIAL
     *
     * @mbg.generated
     */
    public void setHtmlMaterial(String htmlMaterial) {
        this.htmlMaterial = htmlMaterial == null ? null : htmlMaterial.trim();
    }
}